#!/usr/bin/env python
from __future__ import print_function

import rospy
import opendog_ros

if __name__ == '__main__':
    try:
        opendog_ros.start_odrive()
    except rospy.ROSInterruptException:
        pass
